### ISSUE TITLE
PCI Express version is unavailable

### ISSUE THREAD

**Issue by ghost** [schlae/snark-barker#1]
Hello,

This is obviously a joke. I don't know what effort it would take to build such a device.

Congratulation on your impressive work.

Best regards.

**Comment by eflukx** [comment]
Probably it would be "easiest" to employ a PCIe-to-ISA bridge.
An Asix AX99100 probably would do the job (?), another possible approach would be to implement the bridge in an FPGA (Xilinx seems to have the IP cores available to do something similar!)

**Comment by root42** [comment]
Problem with PCIe is that iirc ISA DMA and IRQs will not work with such an adapter… But yeah, a PCIe version would be impressive :)

**Comment by volkertb** [comment]
A Micro Channel (MCA) version would be awesome, though, especially given how rare it is to find sound cards for that architecture. 😄 But given that it's a proprietary bus with less public documentation and only a few systems that support it, I reckon it would be a lot harder to design one than the ISA version was. I guess I should open a separate issue for that, right? 😉

**Comment by root42** [comment]
MCA would be cool, yes. But you need a proprietary interface IC. It seems many cards used the 82c611. However I doubt these are available easily from any of the Chinese suppliers, who sell obsolete ICs...

**Comment by volkertb** [comment]
Interesting. I guess it made sense that a more complex bus would require a dedicated interface controller.

Perhaps such an 82c611 or 82c612 chip could be salvaged from another cheap MCA expansion card? MCA sound cards go for hundreds of dollars on eBay due to their rarity, but I see a lot of MCA NICs going for around $30.

Data sheets can still be found on-line through some quick googling, so based on that, someone savvy enough might be able to design a sound card that would work on PS/2 systems based on the Micro Channel Architecture.

But this would be a **very** niche project, even more niche than a retro ISA sound card. And well beyond my knowledge and skills, I'm afraid. 😅

**Comment by mikedebian** [comment]
https://threadreaderapp.com/thread/1153718213449904128.html

Interesting read about TPM to ISA (shoutout to this project as well.)

**Comment by NukemD** [comment]
> A Micro Channel (MCA) version would be awesome, though, especially given how rare it is to find sound cards for that architecture.  But given that it's a proprietary bus with less public documentation and only a few systems that support it, I reckon it would be a lot harder to design one than the ISA version was. I guess I should open a separate issue for that, right?

There's already a working solution for machines with proprietary slots or without slots at all (ie. laptops or thin clients) called OPL2LPT or the more recent OPL3LPT. It's basically a sound card for the parallel printer port and uses a TSR to reroute port calls. It has very good compatibility with games which don't run in protected mode (DPMI) and decent compatibility mode with games that do via patches.

https://www.serdashop.com/OPL3LPT

**Comment by volkertb** [comment]
> > A Micro Channel (MCA) version would be awesome, though, especially given how rare it is to find sound cards for that architecture.  But given that it's a proprietary bus with less public documentation and only a few systems that support it, I reckon it would be a lot harder to design one than the ISA version was. I guess I should open a separate issue for that, right?
> 
> There's already a working solution for machines with proprietary slots or without slots at all (ie. laptops or thin clients) called OPL2LPT or the more recent OPL3LPT. It's basically a sound card for the parallel printer port and uses a TSR to reroute port calls. It has very good compatibility with games which don't run in protected mode (DPMI) and decent compatibility mode with games that do via patches.
> 
> https://www.serdashop.com/OPL3LPT

I'm aware of the OPL2LPT and OPL3LPT products and they are indeed amazing. However, they only provide an alternative for the FM (music synthesizer) part of Sound Blaster emulation/compatibility. Having a sound device that would plug into a single parallel port while providing compatibility or emulation of both FM synthesis and DAC playback would be ideal. Such devices have been released in the past, but they are hard to find and expensive. Having such a device with an open source design, that would be great.
