### ISSUE TITLE
Replacement for obsolete Mouser parts (152-3415, 512-LM324AN)

### ISSUE THREAD

**Issue by anetanel** [schlae/snark-barker#11]
I'm gathering the parts for a card, using the BOM file in Mouser, but there are 2 items that are marked as obsolete, so I'll need replacements.
1. The 15 pin D-SUB socket ([152-3415](https://www.mouser.co.il/ProductDetail/?qs=oQGaBZOgWEYA4BkUeyODRg%3D%3D)) 
2. The amplifier chip U5 ([512-LM324AN](https://www.mouser.co.il/ProductDetail/?qs=AFLC8Sm4xaWh3GAKvNiiWg%3D%3D)) 

I tried looking for a replacement DSUB connector by selecting all the attributes and looking for similar, and the search came up with [20 items](https://www.mouser.co.il/c/connectors/d-sub-connectors/d-sub-standard-connectors/?contact%20gender=Socket%20%28Female%29&contact%20plating=Gold&filtered=Unfiltered&gender=Female&mounting%20angle=Right%20Angle&mounting%20style=Through%20Hole&number%20of%20positions=15%20Position&number%20of%20rows=2%20Row&shell%20material=Polybutylene%20Terephthalate%20%28PBT%29&shell%20size=2%20%28A%29&termination%20style=Solder%20Pin&type=Receptacle&instock=y&sort=pricing). Can I just grab [the cheapest one](https://www.mouser.co.il/ProductDetail/HARTING/09682537612?qs=8yNGYH%2FU%252B5LaO0VSntI2kw%3D%3D)? :P

And can the amp chip be replaced with this one: https://www.mouser.co.il/ProductDetail/Texas-Instruments/LM324AN?qs=KaAwwOlwapuGsi7hHRxlkw%3D%3D ?
I noticed that it have a bit different "Output Current per Channel" value of 20mA, vs 40mA in the original part.

**Comment by schlae** [comment]
i've swapped in some new parts in the BOM. the TI LM324 should work fine. the d-sub connector is not critical but you must check the distance between the mounting holes on the footprint and the panel edge -- it should be about 9.5mm. some d-subs are "stubby" and won't work.
