### ISSUE TITLE
DSP clarification is required

### ISSUE THREAD

**Issue by rkurbatov** [schlae/snark-barker#14]
Hello and, first of all, thanks for this amazing project.

While I'm waiting for all the remaining parts to arrive, I'd wanted to clarify the DSP functionality.

As I understand, original SB 1.0 had DSP version 1.x that allowed 22kHz playback
SB 1.5 was the same card with C/MS chips removed for the price reason (btw board rev. CT1320C is actually that 1.5 version if I'm not mistaken)
SB 2.0 used custom creative chip instead of plenty discrete logic chips and 8051 (idk if it had 8051 core inside). It supported 44.1 kHz, auto init DMA and its DSP version was 2.01+. 
Then DSP 2.0 update was released for older cards that supported only auto init DMA feature but not affected the playback rate.

There is firmware file in the original repository that has functionality of DSP 2.0 as I understand. Am I correct?

There are two additional firmwares sources - the 'original' one v 2.02 and one from the Chinese clone card.
Are both suitable for the Snark Barker card? What features do they have? That probably means "do they support 44.1kHz playback rate on Snark Barker"?

**Comment by schlae** [comment]
Either will work on the Snark Barker. I don't believe any pre-2.0 DSP versions have been dumped, and both of these firmware files support the higher rate audio and auto init DMA.
