### ISSUE TITLE
DSP ISSUE?

### ISSUE THREAD

**Issue by greukik** [schlae/snark-barker#15]
Hello.

I just finished 2 cards and have the same issue.
Digit is not working. Sbdiag test runs well adlib cms.
Dsp adressing is pulsing on the oscillo. But dsp write test is not pulsing.
I found few people with the same issue on vogons.
I understand that the only common thing is the 89s51 from.mouser and programming from a t48. One important point is that checkid is blocking with a FF FF result and you have to disable checkid in order to flash. I'm not sure but I suspect something there...
Did you flash the atmel with a programmer or with isp method ?

**Comment by schlae** [comment]
which DSP write test isn't pulsing? there are two parts:

1.  ISA_WR signal on U18 pin 8. this is generated by writes to the ISA bus and doesn't require a working 8051. but if this signal is not present, then it is a problem.
2.  DSP_RD signal on U18 pin 1. this is generated by the 8051. if the 8051 has issues then you will not see this pulse. if the ISA_WR signal isn't pulsing, then you will not see this pulse.

i typically flash using the TL866 not with ISP. getting a checkid result of FF FF on the t48 means that there is something wrong with the microcontroller. do you have the correct device selected in the programmer? is it in the socket the right way? (not shifted by one, rotated 180 degrees, etc).

**Comment by greukik** [comment]
Thank you for you response and congrats for your fabulous work.
I have to precise that u18-1 is only 5v without any signal.
On u18-8 i have a nice regular triangle like signal. 
![IMG_20240502_202422](https://github.com/schlae/snark-barker/assets/130314146/8bfc9ecc-cc32-415d-8668-d149a6a2d48a)
![IMG_20240502_202412](https://github.com/schlae/snark-barker/assets/130314146/32a3416d-31e3-4332-bb7d-0f8ee7631c28)

Logical deduction is a disruptive atmel... I must say that I spend two days reading all your schematics (I think I can redraw it from memory :) ) , tested all the logic IC with the t48 and tested all the links with my ohmmeter...

**Comment by greukik** [comment]
Hello. In ordrer to close this topic and help some people, I just received new ATMEL 89S52. 4 from 5 were fonctionnal and work well. So, my 5 atmel from mouser were ALL defective... Now I'm having fun. Thanks !
