### ISSUE TITLE
sbdiag: CMS tests don't always generate a sine wave

### ISSUE THREAD

**Issue by schlae** [schlae/snark-barker#8]
Most likely because the tests fail to initialize all the required registers. Running another CMS-supporting program first and then running sbdiag works.

**Comment by clausecker** [comment]
It was suggested to me that this could also be the result of back to back register writes.  While the card already has a flip flop to slow down access to the SAA1099 chips, maybe that is insufficient when having a fast ISA bus.  Perhaps some dummy port reads can be inserted to slow down the register access.

**Comment by clausecker** [comment]
It [was suggested](https://chat.stackexchange.com/transcript/message/60054433#60054433) that turning off the noise generators before playing a sound might solve the problem.

Testing on my machine, this seems to fix playback of the sine wave.
